name: Build the project
run-name: ${{ github.actor }} Triggered a build 🚀
on: [push]
env:
  NODE_VERSION: 20

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm update
      - run: npm run build
      - name: Archive build result
        uses: actions/upload-artifact@v4
        with:
          name: bar-card.js
          path: dist/bar-card.js

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        if: startsWith(github.event.ref, 'refs/tags/v')
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./bar-card.js
          asset_name: bar-card.js
          asset_content_type: application/javascript
        if: startsWith(github.event.ref, 'refs/tags/v')
        if: startsWith(github.event.ref, 'refs/tags/v')